### ISSUE TITLE
Telegram returned an invalid response! 

### ISSUE THREAD

**Issue by muellerlukas** [mantisbt-plugins/TelegramBot#20]
Hi there,

I just installed 1.3.3 and got  that message. Looked at the Exception and got the info "Received invalid version in initial SOCKS5 response".
When I switch to 1.3.1 it works without problems.
Problem: Proxy is also set, when empty.

**Comment by brlumen** [comment]
Hi @muellerlukas !

Thank you for your contribution to this open project.
This issue has been fixed in PR #19

Now there is a testing phase after which I plan to release a new release.
If you do not mind, take part in testing. PR can be downloaded from the link: 
https://github.com/brlumen/TelegramBot/archive/fix-undefined-variable.zip
